resolver: lts-8.11
packages:
- '.'
- ../common

extra-deps:
  - miso-0.18.0.0
  # Settle on a more recent version of Servant with the backend.
  # NOTE: We are using <0.13 because later versions bumped the Aeson dependency.
  - servant-0.12.1
  - cabal-doctest-1.0.6
allow-newer: true

compiler: ghcjs-0.2.1.9008011_ghc-8.0.2
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9008011_ghc-8.0.2:
        url: https://github.com/matchwood/ghcjs-stack-dist/raw/master/ghcjs-0.2.1.9008011.tar.gz
        sha1: a72a5181124baf64bcd0e68a8726e65914473b3b
