_package-lib: !include "../package-lib.yaml"

name: common
version: "0.1.0.0"
<<: *maintainer

default-extensions: *app-default-extensions-8-0

library:
  source-dirs: src
  ghc-options: *warn-ghc-options
  dependencies:
    - base
    - miso
    - aeson
    - lens
    - containers
    - network-uri
    - servant

tests:
  spec:
    main: Main.hs
    source-dirs: test
    ghc-options: *full-ghc-options
    dependencies:
      - base
      - common
      - hspec
      - servant
