resolver: lts-9.21
packages:
- '.'

extra-deps:
  - miso-0.18.0.0
  # Pin Aeson to the version the frontend uses.
  - aeson-1.1.2.0
  # Settle on a more recent version of Servant with the frontend/backend.
  # NOTE: We are using <0.13 because later versions bumped the Aeson dependency.
  - servant-0.12.1
  - cabal-doctest-1.0.6
  - phoityne-vscode-0.0.22.0
